"use client";

import { useMemo, useState } from "react";

type Check = { name: string; ok: boolean; detail: string };
function inspect(html: string) { const title = (html.match(/<title>([^<]*)<\/title>/i) || [])[1] || ""; const description = (html.match(/name=["']description["'][^>]*content=["']([^"']*)["']/i) || html.match(/content=["']([^"']*)["'][^>]*name=["']description["']/i) || [])[1] || ""; const h1 = (html.match(/<h1[^>]*>([^<]*)<\/h1>/i) || [])[1] || ""; const images = (html.match(/<img\b/gi) || []).length; const imagesWithAlt = (html.match(/<img[^>]*alt=/gi) || []).length; const links = (html.match(/<a\b/gi) || []).length; const checks: Check[] = [{ name: "Title present", ok: title.length > 0, detail: title || "missing" }, { name: "Title length 30–60", ok: title.length >= 30 && title.length <= 60, detail: `${title.length} chars` }, { name: "Meta description", ok: description.length >= 50, detail: `${description.length} chars` }, { name: "H1 present", ok: Boolean(h1), detail: h1 || "missing" }, { name: "Images have alt", ok: images === 0 || imagesWithAlt === images, detail: `${imagesWithAlt}/${images}` }, { name: "Has links", ok: links > 0, detail: String(links) }]; return { checks, score: Math.round((checks.filter((check) => check.ok).length / checks.length) * 100) }; }
const SAMPLE = '<title>Demo Page Title That Is Long Enough</title>\n<meta name="description" content="A demo description that is long enough for SEO checks.">\n<h1>Hello</h1>\n<img src="/x.png" alt="x">\n<a href="/a">A</a>';

export default function Home() {
  const [url, setUrl] = useState("https://bookchaowalit.com");
  const [html, setHtml] = useState(SAMPLE);
  const [copied, setCopied] = useState(false);
  const report = useMemo(() => inspect(html), [html]);
  const copyReport = async () => { try { await navigator.clipboard.writeText(`${url}\nSEO snapshot score: ${report.score}/100\n${report.checks.map((check) => `${check.ok ? "PASS" : "FAIL"} ${check.name} — ${check.detail}`).join("\n")}`); setCopied(true); window.setTimeout(() => setCopied(false), 1500); } catch { setCopied(false); } };
  return <div className="inspector"><main className="inspector-shell"><nav className="inspector-nav"><span><strong>SEO</strong> / INSPECTION BENCH</span><span>LOCAL SNAPSHOT / NO CRAWL</span></nav><header className="inspector-hero"><div><div className="snapshot-note">HTML specimen / live local analysis</div><h1>Find the signal in the markup.</h1></div><p>Paste a page snapshot and read the checks that can be verified here. This tool does not fetch or crawl the URL.</p></header><section className="bench" aria-label="SEO inspection bench"><div className="source-panel"><label className="field-label" htmlFor="source-url">Source label</label><input id="source-url" className="url-field" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="URL (label only)" /><label className="field-label" htmlFor="source-html" style={{ marginTop: 20 }}>HTML snapshot</label><textarea id="source-html" className="html-field" value={html} onChange={(event) => setHtml(event.target.value)} spellCheck={false} /><div className="source-footer"><span>Analysis updates as you type.</span><span className="source-counter">{html.length} chars</span></div></div><div className="report-panel"><div className="report-top"><div><span className="report-label">Lint ledger / result</span><h2>{report.score >= 80 ? "Healthy signal" : report.score >= 50 ? "Needs attention" : "Incomplete signal"}</h2></div><div className="report-score"><strong>{report.score}</strong><span>/100</span><div className="score-bar" role="img" aria-label={`${report.score} out of 100`}><span style={{ width: `${report.score}%` }} /></div></div></div><ul className="check-list">{report.checks.map((check) => <li className="check-row" key={check.name}><span className={`status-mark ${check.ok ? "" : "is-fail"}`} role="img" aria-label={check.ok ? "Pass" : "Fail"} /><span className="check-name">{check.name}</span><span className="check-detail">{check.detail}</span></li>)}</ul><div className="report-actions"><button className="action primary" type="button" onClick={copyReport}>{copied ? "Copied report" : "Copy report"}</button><button className="action" type="button" onClick={() => { setUrl("https://bookchaowalit.com"); setHtml(SAMPLE); }}>Reset sample</button></div><p className="report-foot">Checks are intentionally basic: title, description, heading, image alt text, and links. Treat this as a local inspection aid, not a ranking prediction.</p></div></section><footer className="inspector-footer">The score is derived only from the HTML currently in the editor. No request is sent to the source URL.</footer></main></div>;
}
